/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VillkorRouteImport } from './routes/villkor'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IntegritetspolicyRouteImport } from './routes/integritetspolicy'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AterbetalningRouteImport } from './routes/aterbetalning'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedVannerRouteImport } from './routes/_authenticated/vanner'
import { Route as AuthenticatedReceptRouteImport } from './routes/_authenticated/recept'
import { Route as AuthenticatedProgressRouteImport } from './routes/_authenticated/progress'
import { Route as AuthenticatedProfilRouteImport } from './routes/_authenticated/profil'
import { Route as AuthenticatedOvningarRouteImport } from './routes/_authenticated/ovningar'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedNyttSchemaRouteImport } from './routes/_authenticated/nytt-schema'
import { Route as AuthenticatedNutritionRouteImport } from './routes/_authenticated/nutrition'
import { Route as AuthenticatedKostschemaRouteImport } from './routes/_authenticated/kostschema'
import { Route as AuthenticatedKostplanRouteImport } from './routes/_authenticated/kostplan'
import { Route as AuthenticatedKaloridagbokRouteImport } from './routes/_authenticated/kaloridagbok'
import { Route as AuthenticatedHemRouteImport } from './routes/_authenticated/hem'
import { Route as AuthenticatedHalsaRouteImport } from './routes/_authenticated/halsa'
import { Route as AuthenticatedCommunityRouteImport } from './routes/_authenticated/community'
import { Route as AuthenticatedCoachRouteImport } from './routes/_authenticated/coach'
import { Route as AuthenticatedAnpassaSchemaRouteImport } from './routes/_authenticated/anpassa-schema'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAchievementsRouteImport } from './routes/_authenticated/achievements'
import { Route as AuthenticatedNutritionIndexRouteImport } from './routes/_authenticated/nutrition.index'
import { Route as AuthenticatedSchemaIdRouteImport } from './routes/_authenticated/schema.$id'
import { Route as AuthenticatedPassSchemaIdRouteImport } from './routes/_authenticated/pass.$schemaId'
import { Route as AuthenticatedOvningIdRouteImport } from './routes/_authenticated/ovning.$id'
import { Route as AuthenticatedNutritionOnboardingRouteImport } from './routes/_authenticated/nutrition.onboarding'
import { Route as AuthenticatedNutritionLogRouteImport } from './routes/_authenticated/nutrition.log'
import { Route as AuthenticatedNutritionCoachingRouteImport } from './routes/_authenticated/nutrition.coaching'
import { Route as AuthenticatedNutritionAnalyticsRouteImport } from './routes/_authenticated/nutrition.analytics'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const VillkorRoute = VillkorRouteImport.update({
  id: '/villkor',
  path: '/villkor',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegritetspolicyRoute = IntegritetspolicyRouteImport.update({
  id: '/integritetspolicy',
  path: '/integritetspolicy',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AterbetalningRoute = AterbetalningRouteImport.update({
  id: '/aterbetalning',
  path: '/aterbetalning',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVannerRoute = AuthenticatedVannerRouteImport.update({
  id: '/vanner',
  path: '/vanner',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReceptRoute = AuthenticatedReceptRouteImport.update({
  id: '/recept',
  path: '/recept',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProgressRoute = AuthenticatedProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfilRoute = AuthenticatedProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOvningarRoute = AuthenticatedOvningarRouteImport.update({
  id: '/ovningar',
  path: '/ovningar',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNyttSchemaRoute = AuthenticatedNyttSchemaRouteImport.update({
  id: '/nytt-schema',
  path: '/nytt-schema',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNutritionRoute = AuthenticatedNutritionRouteImport.update({
  id: '/nutrition',
  path: '/nutrition',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedKostschemaRoute = AuthenticatedKostschemaRouteImport.update({
  id: '/kostschema',
  path: '/kostschema',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedKostplanRoute = AuthenticatedKostplanRouteImport.update({
  id: '/kostplan',
  path: '/kostplan',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedKaloridagbokRoute =
  AuthenticatedKaloridagbokRouteImport.update({
    id: '/kaloridagbok',
    path: '/kaloridagbok',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHemRoute = AuthenticatedHemRouteImport.update({
  id: '/hem',
  path: '/hem',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHalsaRoute = AuthenticatedHalsaRouteImport.update({
  id: '/halsa',
  path: '/halsa',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCommunityRoute = AuthenticatedCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCoachRoute = AuthenticatedCoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAnpassaSchemaRoute =
  AuthenticatedAnpassaSchemaRouteImport.update({
    id: '/anpassa-schema',
    path: '/anpassa-schema',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAchievementsRoute =
  AuthenticatedAchievementsRouteImport.update({
    id: '/achievements',
    path: '/achievements',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedNutritionIndexRoute =
  AuthenticatedNutritionIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedNutritionRoute,
  } as any)
const AuthenticatedSchemaIdRoute = AuthenticatedSchemaIdRouteImport.update({
  id: '/schema/$id',
  path: '/schema/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPassSchemaIdRoute =
  AuthenticatedPassSchemaIdRouteImport.update({
    id: '/pass/$schemaId',
    path: '/pass/$schemaId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOvningIdRoute = AuthenticatedOvningIdRouteImport.update({
  id: '/ovning/$id',
  path: '/ovning/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNutritionOnboardingRoute =
  AuthenticatedNutritionOnboardingRouteImport.update({
    id: '/onboarding',
    path: '/onboarding',
    getParentRoute: () => AuthenticatedNutritionRoute,
  } as any)
const AuthenticatedNutritionLogRoute =
  AuthenticatedNutritionLogRouteImport.update({
    id: '/log',
    path: '/log',
    getParentRoute: () => AuthenticatedNutritionRoute,
  } as any)
const AuthenticatedNutritionCoachingRoute =
  AuthenticatedNutritionCoachingRouteImport.update({
    id: '/coaching',
    path: '/coaching',
    getParentRoute: () => AuthenticatedNutritionRoute,
  } as any)
const AuthenticatedNutritionAnalyticsRoute =
  AuthenticatedNutritionAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedNutritionRoute,
  } as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aterbetalning': typeof AterbetalningRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/integritetspolicy': typeof IntegritetspolicyRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/villkor': typeof VillkorRoute
  '/achievements': typeof AuthenticatedAchievementsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/anpassa-schema': typeof AuthenticatedAnpassaSchemaRoute
  '/coach': typeof AuthenticatedCoachRoute
  '/community': typeof AuthenticatedCommunityRoute
  '/halsa': typeof AuthenticatedHalsaRoute
  '/hem': typeof AuthenticatedHemRoute
  '/kaloridagbok': typeof AuthenticatedKaloridagbokRoute
  '/kostplan': typeof AuthenticatedKostplanRoute
  '/kostschema': typeof AuthenticatedKostschemaRoute
  '/nutrition': typeof AuthenticatedNutritionRouteWithChildren
  '/nytt-schema': typeof AuthenticatedNyttSchemaRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/ovningar': typeof AuthenticatedOvningarRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/progress': typeof AuthenticatedProgressRoute
  '/recept': typeof AuthenticatedReceptRoute
  '/vanner': typeof AuthenticatedVannerRoute
  '/nutrition/analytics': typeof AuthenticatedNutritionAnalyticsRoute
  '/nutrition/coaching': typeof AuthenticatedNutritionCoachingRoute
  '/nutrition/log': typeof AuthenticatedNutritionLogRoute
  '/nutrition/onboarding': typeof AuthenticatedNutritionOnboardingRoute
  '/ovning/$id': typeof AuthenticatedOvningIdRoute
  '/pass/$schemaId': typeof AuthenticatedPassSchemaIdRoute
  '/schema/$id': typeof AuthenticatedSchemaIdRoute
  '/nutrition/': typeof AuthenticatedNutritionIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aterbetalning': typeof AterbetalningRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/integritetspolicy': typeof IntegritetspolicyRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/villkor': typeof VillkorRoute
  '/achievements': typeof AuthenticatedAchievementsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/anpassa-schema': typeof AuthenticatedAnpassaSchemaRoute
  '/coach': typeof AuthenticatedCoachRoute
  '/community': typeof AuthenticatedCommunityRoute
  '/halsa': typeof AuthenticatedHalsaRoute
  '/hem': typeof AuthenticatedHemRoute
  '/kaloridagbok': typeof AuthenticatedKaloridagbokRoute
  '/kostplan': typeof AuthenticatedKostplanRoute
  '/kostschema': typeof AuthenticatedKostschemaRoute
  '/nytt-schema': typeof AuthenticatedNyttSchemaRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/ovningar': typeof AuthenticatedOvningarRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/progress': typeof AuthenticatedProgressRoute
  '/recept': typeof AuthenticatedReceptRoute
  '/vanner': typeof AuthenticatedVannerRoute
  '/nutrition/analytics': typeof AuthenticatedNutritionAnalyticsRoute
  '/nutrition/coaching': typeof AuthenticatedNutritionCoachingRoute
  '/nutrition/log': typeof AuthenticatedNutritionLogRoute
  '/nutrition/onboarding': typeof AuthenticatedNutritionOnboardingRoute
  '/ovning/$id': typeof AuthenticatedOvningIdRoute
  '/pass/$schemaId': typeof AuthenticatedPassSchemaIdRoute
  '/schema/$id': typeof AuthenticatedSchemaIdRoute
  '/nutrition': typeof AuthenticatedNutritionIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/aterbetalning': typeof AterbetalningRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/integritetspolicy': typeof IntegritetspolicyRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/villkor': typeof VillkorRoute
  '/_authenticated/achievements': typeof AuthenticatedAchievementsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/anpassa-schema': typeof AuthenticatedAnpassaSchemaRoute
  '/_authenticated/coach': typeof AuthenticatedCoachRoute
  '/_authenticated/community': typeof AuthenticatedCommunityRoute
  '/_authenticated/halsa': typeof AuthenticatedHalsaRoute
  '/_authenticated/hem': typeof AuthenticatedHemRoute
  '/_authenticated/kaloridagbok': typeof AuthenticatedKaloridagbokRoute
  '/_authenticated/kostplan': typeof AuthenticatedKostplanRoute
  '/_authenticated/kostschema': typeof AuthenticatedKostschemaRoute
  '/_authenticated/nutrition': typeof AuthenticatedNutritionRouteWithChildren
  '/_authenticated/nytt-schema': typeof AuthenticatedNyttSchemaRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/ovningar': typeof AuthenticatedOvningarRoute
  '/_authenticated/profil': typeof AuthenticatedProfilRoute
  '/_authenticated/progress': typeof AuthenticatedProgressRoute
  '/_authenticated/recept': typeof AuthenticatedReceptRoute
  '/_authenticated/vanner': typeof AuthenticatedVannerRoute
  '/_authenticated/nutrition/analytics': typeof AuthenticatedNutritionAnalyticsRoute
  '/_authenticated/nutrition/coaching': typeof AuthenticatedNutritionCoachingRoute
  '/_authenticated/nutrition/log': typeof AuthenticatedNutritionLogRoute
  '/_authenticated/nutrition/onboarding': typeof AuthenticatedNutritionOnboardingRoute
  '/_authenticated/ovning/$id': typeof AuthenticatedOvningIdRoute
  '/_authenticated/pass/$schemaId': typeof AuthenticatedPassSchemaIdRoute
  '/_authenticated/schema/$id': typeof AuthenticatedSchemaIdRoute
  '/_authenticated/nutrition/': typeof AuthenticatedNutritionIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aterbetalning'
    | '/forgot-password'
    | '/integritetspolicy'
    | '/login'
    | '/pricing'
    | '/reset-password'
    | '/sitemap.xml'
    | '/villkor'
    | '/achievements'
    | '/admin'
    | '/anpassa-schema'
    | '/coach'
    | '/community'
    | '/halsa'
    | '/hem'
    | '/kaloridagbok'
    | '/kostplan'
    | '/kostschema'
    | '/nutrition'
    | '/nytt-schema'
    | '/onboarding'
    | '/ovningar'
    | '/profil'
    | '/progress'
    | '/recept'
    | '/vanner'
    | '/nutrition/analytics'
    | '/nutrition/coaching'
    | '/nutrition/log'
    | '/nutrition/onboarding'
    | '/ovning/$id'
    | '/pass/$schemaId'
    | '/schema/$id'
    | '/nutrition/'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aterbetalning'
    | '/forgot-password'
    | '/integritetspolicy'
    | '/login'
    | '/pricing'
    | '/reset-password'
    | '/sitemap.xml'
    | '/villkor'
    | '/achievements'
    | '/admin'
    | '/anpassa-schema'
    | '/coach'
    | '/community'
    | '/halsa'
    | '/hem'
    | '/kaloridagbok'
    | '/kostplan'
    | '/kostschema'
    | '/nytt-schema'
    | '/onboarding'
    | '/ovningar'
    | '/profil'
    | '/progress'
    | '/recept'
    | '/vanner'
    | '/nutrition/analytics'
    | '/nutrition/coaching'
    | '/nutrition/log'
    | '/nutrition/onboarding'
    | '/ovning/$id'
    | '/pass/$schemaId'
    | '/schema/$id'
    | '/nutrition'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/aterbetalning'
    | '/forgot-password'
    | '/integritetspolicy'
    | '/login'
    | '/pricing'
    | '/reset-password'
    | '/sitemap.xml'
    | '/villkor'
    | '/_authenticated/achievements'
    | '/_authenticated/admin'
    | '/_authenticated/anpassa-schema'
    | '/_authenticated/coach'
    | '/_authenticated/community'
    | '/_authenticated/halsa'
    | '/_authenticated/hem'
    | '/_authenticated/kaloridagbok'
    | '/_authenticated/kostplan'
    | '/_authenticated/kostschema'
    | '/_authenticated/nutrition'
    | '/_authenticated/nytt-schema'
    | '/_authenticated/onboarding'
    | '/_authenticated/ovningar'
    | '/_authenticated/profil'
    | '/_authenticated/progress'
    | '/_authenticated/recept'
    | '/_authenticated/vanner'
    | '/_authenticated/nutrition/analytics'
    | '/_authenticated/nutrition/coaching'
    | '/_authenticated/nutrition/log'
    | '/_authenticated/nutrition/onboarding'
    | '/_authenticated/ovning/$id'
    | '/_authenticated/pass/$schemaId'
    | '/_authenticated/schema/$id'
    | '/_authenticated/nutrition/'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AterbetalningRoute: typeof AterbetalningRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  IntegritetspolicyRoute: typeof IntegritetspolicyRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  VillkorRoute: typeof VillkorRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/villkor': {
      id: '/villkor'
      path: '/villkor'
      fullPath: '/villkor'
      preLoaderRoute: typeof VillkorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integritetspolicy': {
      id: '/integritetspolicy'
      path: '/integritetspolicy'
      fullPath: '/integritetspolicy'
      preLoaderRoute: typeof IntegritetspolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aterbetalning': {
      id: '/aterbetalning'
      path: '/aterbetalning'
      fullPath: '/aterbetalning'
      preLoaderRoute: typeof AterbetalningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/vanner': {
      id: '/_authenticated/vanner'
      path: '/vanner'
      fullPath: '/vanner'
      preLoaderRoute: typeof AuthenticatedVannerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/recept': {
      id: '/_authenticated/recept'
      path: '/recept'
      fullPath: '/recept'
      preLoaderRoute: typeof AuthenticatedReceptRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/progress': {
      id: '/_authenticated/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof AuthenticatedProgressRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profil': {
      id: '/_authenticated/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof AuthenticatedProfilRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ovningar': {
      id: '/_authenticated/ovningar'
      path: '/ovningar'
      fullPath: '/ovningar'
      preLoaderRoute: typeof AuthenticatedOvningarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/nytt-schema': {
      id: '/_authenticated/nytt-schema'
      path: '/nytt-schema'
      fullPath: '/nytt-schema'
      preLoaderRoute: typeof AuthenticatedNyttSchemaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/nutrition': {
      id: '/_authenticated/nutrition'
      path: '/nutrition'
      fullPath: '/nutrition'
      preLoaderRoute: typeof AuthenticatedNutritionRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/kostschema': {
      id: '/_authenticated/kostschema'
      path: '/kostschema'
      fullPath: '/kostschema'
      preLoaderRoute: typeof AuthenticatedKostschemaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/kostplan': {
      id: '/_authenticated/kostplan'
      path: '/kostplan'
      fullPath: '/kostplan'
      preLoaderRoute: typeof AuthenticatedKostplanRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/kaloridagbok': {
      id: '/_authenticated/kaloridagbok'
      path: '/kaloridagbok'
      fullPath: '/kaloridagbok'
      preLoaderRoute: typeof AuthenticatedKaloridagbokRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hem': {
      id: '/_authenticated/hem'
      path: '/hem'
      fullPath: '/hem'
      preLoaderRoute: typeof AuthenticatedHemRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/halsa': {
      id: '/_authenticated/halsa'
      path: '/halsa'
      fullPath: '/halsa'
      preLoaderRoute: typeof AuthenticatedHalsaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/community': {
      id: '/_authenticated/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof AuthenticatedCommunityRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/coach': {
      id: '/_authenticated/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof AuthenticatedCoachRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/anpassa-schema': {
      id: '/_authenticated/anpassa-schema'
      path: '/anpassa-schema'
      fullPath: '/anpassa-schema'
      preLoaderRoute: typeof AuthenticatedAnpassaSchemaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/achievements': {
      id: '/_authenticated/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AuthenticatedAchievementsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/nutrition/': {
      id: '/_authenticated/nutrition/'
      path: '/'
      fullPath: '/nutrition/'
      preLoaderRoute: typeof AuthenticatedNutritionIndexRouteImport
      parentRoute: typeof AuthenticatedNutritionRoute
    }
    '/_authenticated/schema/$id': {
      id: '/_authenticated/schema/$id'
      path: '/schema/$id'
      fullPath: '/schema/$id'
      preLoaderRoute: typeof AuthenticatedSchemaIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pass/$schemaId': {
      id: '/_authenticated/pass/$schemaId'
      path: '/pass/$schemaId'
      fullPath: '/pass/$schemaId'
      preLoaderRoute: typeof AuthenticatedPassSchemaIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ovning/$id': {
      id: '/_authenticated/ovning/$id'
      path: '/ovning/$id'
      fullPath: '/ovning/$id'
      preLoaderRoute: typeof AuthenticatedOvningIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/nutrition/onboarding': {
      id: '/_authenticated/nutrition/onboarding'
      path: '/onboarding'
      fullPath: '/nutrition/onboarding'
      preLoaderRoute: typeof AuthenticatedNutritionOnboardingRouteImport
      parentRoute: typeof AuthenticatedNutritionRoute
    }
    '/_authenticated/nutrition/log': {
      id: '/_authenticated/nutrition/log'
      path: '/log'
      fullPath: '/nutrition/log'
      preLoaderRoute: typeof AuthenticatedNutritionLogRouteImport
      parentRoute: typeof AuthenticatedNutritionRoute
    }
    '/_authenticated/nutrition/coaching': {
      id: '/_authenticated/nutrition/coaching'
      path: '/coaching'
      fullPath: '/nutrition/coaching'
      preLoaderRoute: typeof AuthenticatedNutritionCoachingRouteImport
      parentRoute: typeof AuthenticatedNutritionRoute
    }
    '/_authenticated/nutrition/analytics': {
      id: '/_authenticated/nutrition/analytics'
      path: '/analytics'
      fullPath: '/nutrition/analytics'
      preLoaderRoute: typeof AuthenticatedNutritionAnalyticsRouteImport
      parentRoute: typeof AuthenticatedNutritionRoute
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedNutritionRouteChildren {
  AuthenticatedNutritionAnalyticsRoute: typeof AuthenticatedNutritionAnalyticsRoute
  AuthenticatedNutritionCoachingRoute: typeof AuthenticatedNutritionCoachingRoute
  AuthenticatedNutritionLogRoute: typeof AuthenticatedNutritionLogRoute
  AuthenticatedNutritionOnboardingRoute: typeof AuthenticatedNutritionOnboardingRoute
  AuthenticatedNutritionIndexRoute: typeof AuthenticatedNutritionIndexRoute
}

const AuthenticatedNutritionRouteChildren: AuthenticatedNutritionRouteChildren =
  {
    AuthenticatedNutritionAnalyticsRoute: AuthenticatedNutritionAnalyticsRoute,
    AuthenticatedNutritionCoachingRoute: AuthenticatedNutritionCoachingRoute,
    AuthenticatedNutritionLogRoute: AuthenticatedNutritionLogRoute,
    AuthenticatedNutritionOnboardingRoute:
      AuthenticatedNutritionOnboardingRoute,
    AuthenticatedNutritionIndexRoute: AuthenticatedNutritionIndexRoute,
  }

const AuthenticatedNutritionRouteWithChildren =
  AuthenticatedNutritionRoute._addFileChildren(
    AuthenticatedNutritionRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAchievementsRoute: typeof AuthenticatedAchievementsRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAnpassaSchemaRoute: typeof AuthenticatedAnpassaSchemaRoute
  AuthenticatedCoachRoute: typeof AuthenticatedCoachRoute
  AuthenticatedCommunityRoute: typeof AuthenticatedCommunityRoute
  AuthenticatedHalsaRoute: typeof AuthenticatedHalsaRoute
  AuthenticatedHemRoute: typeof AuthenticatedHemRoute
  AuthenticatedKaloridagbokRoute: typeof AuthenticatedKaloridagbokRoute
  AuthenticatedKostplanRoute: typeof AuthenticatedKostplanRoute
  AuthenticatedKostschemaRoute: typeof AuthenticatedKostschemaRoute
  AuthenticatedNutritionRoute: typeof AuthenticatedNutritionRouteWithChildren
  AuthenticatedNyttSchemaRoute: typeof AuthenticatedNyttSchemaRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedOvningarRoute: typeof AuthenticatedOvningarRoute
  AuthenticatedProfilRoute: typeof AuthenticatedProfilRoute
  AuthenticatedProgressRoute: typeof AuthenticatedProgressRoute
  AuthenticatedReceptRoute: typeof AuthenticatedReceptRoute
  AuthenticatedVannerRoute: typeof AuthenticatedVannerRoute
  AuthenticatedOvningIdRoute: typeof AuthenticatedOvningIdRoute
  AuthenticatedPassSchemaIdRoute: typeof AuthenticatedPassSchemaIdRoute
  AuthenticatedSchemaIdRoute: typeof AuthenticatedSchemaIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAchievementsRoute: AuthenticatedAchievementsRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAnpassaSchemaRoute: AuthenticatedAnpassaSchemaRoute,
  AuthenticatedCoachRoute: AuthenticatedCoachRoute,
  AuthenticatedCommunityRoute: AuthenticatedCommunityRoute,
  AuthenticatedHalsaRoute: AuthenticatedHalsaRoute,
  AuthenticatedHemRoute: AuthenticatedHemRoute,
  AuthenticatedKaloridagbokRoute: AuthenticatedKaloridagbokRoute,
  AuthenticatedKostplanRoute: AuthenticatedKostplanRoute,
  AuthenticatedKostschemaRoute: AuthenticatedKostschemaRoute,
  AuthenticatedNutritionRoute: AuthenticatedNutritionRouteWithChildren,
  AuthenticatedNyttSchemaRoute: AuthenticatedNyttSchemaRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedOvningarRoute: AuthenticatedOvningarRoute,
  AuthenticatedProfilRoute: AuthenticatedProfilRoute,
  AuthenticatedProgressRoute: AuthenticatedProgressRoute,
  AuthenticatedReceptRoute: AuthenticatedReceptRoute,
  AuthenticatedVannerRoute: AuthenticatedVannerRoute,
  AuthenticatedOvningIdRoute: AuthenticatedOvningIdRoute,
  AuthenticatedPassSchemaIdRoute: AuthenticatedPassSchemaIdRoute,
  AuthenticatedSchemaIdRoute: AuthenticatedSchemaIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AterbetalningRoute: AterbetalningRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  IntegritetspolicyRoute: IntegritetspolicyRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  VillkorRoute: VillkorRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
